services:
  - type: web
    name: b3sa3-api
    env: python
    region: oregon  # Free tier dispon√≠vel
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://predictfinance_gb6k_user:NVqykY12EDGSl5fOee0MYUc7YaW64wIS@dpg-d5c2tcruibrs73cs32pg-a.ohio-postgres.render.com/predictfinance_gb6k
